version: '3.2'

services:
  mysql:
    image: 'mysql:5.7.21'
    container_name: 'mysql_container'
    ports:
      - '33006:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=demo
    command: mysqld --lower_case_table_names=1 --skip-ssl --character-set-server=utf8 --collation-server=utf8_general_ci
